export const WEBPROJECTS = [
  { name: 'My Mentor', description: 'Online mentoring platform', coverPhoto: './mymentor.jpg',url:'',type:'Individual Efforts', status:'Unpublished' },
  { name: 'Mutasim Nimir Centre', description: 'Mutasim Nimir Centre for Environmental Culture official website', coverPhoto: './mncec.png',url:'https://nimir.center/',type:'Team Efforts',status:'Live' },
  { name: 'Eptikar IT Solutions', description: 'The company\'s official website', coverPhoto: './eitwebsite.png',url:'https://eptikar.com/',type:'Team Efforts' ,status:'Live' },
  { name: 'Savannah Innovation Labs', description: 'The organization\'s official website', coverPhoto: './savannah.png',url:'https://savannah.sd/',type:'Individual Efforts' ,status:'Live' },
  { name: 'CivilEd', description: 'Online learning platform', coverPhoto: './CivilEd.png',url:'',type:'Individual Efforts' ,status:'Private' },
  { name: 'Damancash Donation Campaign', description: 'Online donations website', coverPhoto: './donation.png',url:'https://donate.damancash.com/',type:'Team Efforts',status:'Live' },
  { name: 'Damancash Placeholder website', description: 'Coming soon placeholder website', coverPhoto: './comingsoon.png',url:'https://damancash.com/',type:'Team Efforts',status:'Live' },
  { name: 'Damancash FAQ Page', description: 'Frequentrly asked questions page for Damancash application', coverPhoto: './faq.png',url:'https://damancash.com/faq.html',type:'Team Efforts',status:'Live' },
  { name: 'Damancash Waiting List', description: 'Waiting list for damancash application', coverPhoto: './waitinglist.png',url:'',type:'Team Efforts',status:'Private' },
  { name: 'ECCS', description: 'European Chamber of Commerce in Sudan official website', coverPhoto: './eccs.png',url:'https://eccs.sd/',type:'Team Efforts',status:'Live' },
  { name: 'Sudan National Business Agenda', description: 'The project\'s official website', coverPhoto: './nba.png',url:'',type:'Team Efforts',status:'Private' },
  { name: 'My Personal Portfolio V 1.0', description: 'The previous version of my portfolio', coverPhoto: './portfolio.png',url:'',type:'Individual Efforts',status:'Unpublished' },
  { name: 'My Personal Portfolio V 2.0', description: 'This current version of my portfolio', coverPhoto: './portfolio_2.png',url:'./',type:'Individual Efforts',status:'Live' },
  // { name: 'Bawader ICT Solutions', description: 'The company\'s official website', coverPhoto: './bawader_ict.png',url:'',type:'Team Efforts',status:'Unpublished' },
  // { name: 'Kwenda', description: 'Flight Booking Engine', coverPhoto: './kwenda.png',url:'',type:'Team Efforts',status:'Private' },
];

export const UIPROJECTS = [
  { name: 'My Mentor wireframe', description: 'Online mentoring platform web design using figma', coverPhoto: './mymenotr_ui.png',url:'https://www.figma.com/file/3QR2g22o4YEYf3yWwyoKxv/Untitled?node-id=0%3A1&t=ZToWNpkJEvc9AJ7Z-1',status:'Figma'},
  { name: 'Import and export platform wirframe', description: 'Online Import and export platform web design using figma', coverPhoto: './import_export_platform.png',url:'https://www.figma.com/file/hIOaYUzpGYX4qd5ysz3dKF/import%2Fexport?node-id=0%3A1&t=ZToWNpkJEvc9AJ7Z-1',status:'Figma'},
  { name: 'Mutasim Nimir Centre', description: 'Mutasim Nimir Centre for Environmental Culture official website', coverPhoto: './mncec.png',url:'https://nimir.center/',status:'Live'},
  { name: 'Eptikar IT Solutions', description: 'The company\'s official website', coverPhoto: './eitwebsite.png',url:'https://eptikar.com/',status:'Live'},
  { name: 'Savannah Innovation Labs', description: 'The organization\'s official website', coverPhoto: './savannah.png',url:'https://savannah.sd/',status:'Live'},
  { name: 'CivilEd', description: 'Online learning platform', coverPhoto: './CivilEd.png',url:'',status:'Private'},
  {name: 'Damancash Donation Campaign', description: 'Online donations website', coverPhoto: './donation.png',url:'https://donate.damancash.com/',status:'Live' },
  { name: 'Damancash Placeholder website', description: 'Coming soon placeholder website', coverPhoto: './comingsoon.png',url:'https://damancash.com/',status:'Live' },
  { name: 'Damancash FAQ Page', description: 'Frequentrly asked questions page for Damancash application', coverPhoto: './faq.png',url:'https://damancash.com/faq.html',status:'Live' },
  { name: 'Damancash Waiting List', description: 'Waiting list for damancash application', coverPhoto: './waitinglist.png',url:'',status:'Private' },
  { name: 'ECCS', description: 'European Chamber of Commerce in Sudan official website', coverPhoto: './eccs.png',url:'https://eccs.sd/',status:'Live'},
  { name: 'Sudan National Business Agenda', description: 'The project\'s official website', coverPhoto: './nba.png',url:'',status:'Private'},
  { name: 'My Personal Portfolio V 1.0', description: 'The previous version of my portfolio', coverPhoto: './portfolio.png',url:'',status:'Unpublished'},
  { name: 'My Personal Portfolio V 2.0', description: 'The current version of my portfolio', coverPhoto: './portfolio_2.png',url:'/',status:'Live'},
  { name: 'SEF Academy Website Design', description: 'Online Learning platform', coverPhoto: './seff.png',url:'https://www.figma.com/file/epTyd8DXLgF7xrYIdcaJmv/SEFF?type=design&node-id=0%3A1&mode=design&t=y8vNoZes1dYkYdQj-1',status:'Figma'},
  // { name: 'Kwenda', description: 'Flight Booking Engine', coverPhoto: './kwenda.png',url:'',status:'Private' },
  // { name: 'Bawader ICT Solutions', description: 'The company\'s official website', coverPhoto: './bawader_ict.png',url:'',status:'Private' },
  { name: 'Ideal Skin Services', description: 'Beauty Salon Booking Website', coverPhoto: './idealskinservices.png',url:'https://www.figma.com/file/KhGQ9f9d0nH24V30Iq27mM/Ideal-Skin-Services?type=design&node-id=0%3A1&mode=design&t=9ZgECD59Wz2l1Vvf-1',status:'Figma' },
];